### ISSUE TITLE
Custom Wakeword

### ISSUE THREAD

**Issue by silverdesignerdeveloper** [alan-ai/alan-sdk-reactnative#10]
hi could you create a custom wake-word?

**Comment by snyuryev** [comment]
Hi @silverdesignerdeveloper 
We are working on adding custom wake word functionality.

**Comment by silverdesignerdeveloper** [comment]
I think it would be great to be able to create it through reactnatice picovoice libraries or as spokestacks by changing the wakeword by changing it as a string without the need for audio files

**Comment by JamieDawson** [comment]
@silverdesignerdeveloper, 
We can provide a custom wake word as a special feature for the premium paid plan. Please submit a request at  sales@alan.app to receive a quote.
