### ISSUE TITLE
Alan Button not shown in android 

### ISSUE THREAD

**Issue by sharma12343** [alan-ai/alan-sdk-reactnative#11]

**Comment by snyuryev** [comment]
@sharma12343 Could you provide more information about your project please?
What is Android OS version? What is plugin version?

**Comment by sharma12343** [comment]
Plugin version : "@alan-ai/alan-sdk-react-native": "^1.2.0",
Android OS : android 10

**Comment by snyuryev** [comment]
@sharma12343 please update to the latest 1.3.0

**Comment by sharma12343** [comment]
> @sharma12343 please update to the latest 1.3.0

Will check
Thanks

**Comment by sharma12343** [comment]
@snyuryev Getting below exception after version updated.
 java.lang.UnsatisfiedLinkError: dlopen failed: library "libAlanBase.so" not found

**Comment by sharma12343** [comment]
@snyuryev I manual linked Alan package in android. Now its working 
Thanks

**Comment by snyuryev** [comment]
@sharma12343 Got it.
Thank you!

**Comment by saravana05** [comment]
> @snyuryev I manual linked Alan package in android. Now its working
> Thanks

how do you link manually can you share the details here
