### ISSUE TITLE
setVisualState method does not support Array type data

### ISSUE THREAD

**Issue by Somnus007** [alan-ai/alan-sdk-reactnative#15]
Versions:
Device OS version: Android 9
React native version: 0.66.3
@alan-ai/alan-sdk-react-native: 1.8.0

Integrate code:

Subscribe

import {NativeEventEmitter, NativeModules} from 'react-native';
const {AlanManager, AlanEventEmitter} = NativeModules;
const alanEventEmitter = new NativeEventEmitter(AlanEventEmitter);
const alanSubscriber = alanEventEmitter.addListener('command', data => {
  console.log(`got command event ${JSON.stringify(data)}`);
});
Alan Button

{alanKey && <AlanView projectid={alanKey} />}

Description:

- In the voice script
```
onVisualState((p, s) => {
    console.log(s)
});
```
- Run app on Android device, try to set visual state
```
AlanManager.setVisualState({
        bool: true,
        string: 'haha',
        number: 123,
        array: [ 'q', 'w', 'e', 'r'],
        object: {
          name: 'allen',
          isTest: true,
        },
      });
```
- I can only get `{ bool: true, number: 123, object: { isWorking: true, name: 'allen' }, string: 'haha' }` from `onVisualState`, missing `array: [ 'q', 'w', 'e', 'r'],`
- Try to set the same visual state on debug mode of Alan AI console, `onVisualState` returns full data.

**Comment by snyuryev** [comment]
Fixed with version 1.10.0
