### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by silverdesignerdeveloper** [alan-ai/alan-sdk-reactnative#20]
Hi, kind staff, could I ask if it was possible to change Alan's image and be able to put a Gif?  eventually I could modify the interface of him and customize it to my liking?

**Comment by silverdesignerdeveloper** [comment]
how much upload limit do i have to upload my gif?  I could make a list of gifs of my assistant and show a gif for each time he responds differently

**Comment by snyuryev** [comment]
@silverdesignerdeveloper Yes, it is possible to add custom logo (even gif one). [Replacing the Alan logo](https://alan.app/docs/usage/button/customization/#replacing-the-alan-logo)

**Comment by silverdesignerdeveloper** [comment]
ok but it's a static replacement, i was wondering if i could use a gif for each custom intent
