### ISSUE TITLE
Can not wake alan via "Hey Alan"

### ISSUE THREAD

**Issue by Somnus007** [alan-ai/alan-sdk-reactnative#26]
Since @alan-ai/alan-sdk-react-native@2.1.0, I can not wake alan via "Hey Alan", I'm using 1.20.0 now, it works well

**Comment by snyuryev** [comment]
@Somnus007
What platform do you use? Do you have any logs?

**Comment by snyuryev** [comment]
@Somnus007 you can try to collect logs with logcat - https://developer.android.com/tools/logcat
Also if you can send to us minimal reproducible example - we can run it on our side.

**Comment by snyuryev** [comment]
@Somnus007
New version is available to install - https://www.npmjs.com/package/@alan-ai/alan-sdk-react-native/v/2.8.0
Let me know does it fix the issue.

**Comment by snyuryev** [comment]
Hi @Somnus007 
Thank you for your feedback. I would like to close this issue since it is resolved. 
Could you please provide audio examples with wake word activation (which are not working).
