### ISSUE TITLE
Can't import AlanView

### ISSUE THREAD

**Issue by kestvir** [alan-ai/alan-sdk-reactnative#8]
Hello, I'm using Windows and "expo": "~39.0.2" and tried to import `AlanView` like this:  
`import { AlanView } from "@alan-ai/alan-sdk-react-native/AlanSDK"`

However, I got this error:

![err](https://user-images.githubusercontent.com/25966281/105024740-225a5f00-5a55-11eb-9abf-d4b30bd98ffe.PNG)

I also tried copying files: `AllanButton`, `AlanSDK`, `AlanText` from node modules to the root app directory manually, but then got these errors: 
![err2](https://user-images.githubusercontent.com/25966281/105025117-90068b00-5a55-11eb-8699-ac73f9e2d226.PNG)
![err3](https://user-images.githubusercontent.com/25966281/105025118-9137b800-5a55-11eb-96f7-625736e24167.PNG)

Is there something wrong about how I'm importing the files or is it expo, or maybe some other issue?

**Comment by snyuryev** [comment]
@kestvir Hey
Do you have the same error with [test application](https://github.com/alan-ai/alan-sdk-reactnative/tree/master/examples/testapp)?

**Comment by kestvir** [comment]
> @kestvir Hey
> Do you have the same error with [test application](https://github.com/alan-ai/alan-sdk-reactnative/tree/master/examples/testapp)?
> 
> Also we have [this tutorial](https://alan.app/docs/client-api/cross-platform/react-native) for React native integration

Thank you for the quick reply.

Just tried the test app and everything seems to work fine, no errors.

I tried to follow the tutorial, but got confused, because it says to install  `@alan-ai/alan-sdk-react-native `, but then asks to 
import `{ AlanView } from './AlanSDK.js';` Therefore I tried to import `AlanView` from the installed package, just as mentioned above, but got the first error. Then I tried to copy over the files into the main app root and import `AlanView` like in the test app, but then the second and third errors surfaced, as showed in the first post.

**Comment by snyuryev** [comment]
@kestvir 
`AlanSDK.js` and other files should be copied to your project automatically (post install step after `npm i @alan-ai/alan-sdk-react-native`). 
Please use `{ AlanView } from './AlanSDK.js';` in your project - otherwise you will get this error from RN.

**Comment by kestvir** [comment]
> @kestvir
> `AlanSDK.js` and other files should be copied to your project automatically (post install step after `npm i @alan-ai/alan-sdk-react-native`).
> Please use `{ AlanView } from './AlanSDK.js';` in your project - otherwise you will get this error from RN.

Sorry for asking, but for clarification, are those automatically installed files supposed to be inside` node_modules\@alan-ai\alan-sdk-react-native` or in the root of my app?

**Comment by snyuryev** [comment]
@kestvir 
yes, it should be inside of your project folder.

Also could you try to create a new project and install Alan SDK with next commands?
```
npx react-native init AwesomeProject
cd AwesomeProject/
npm i @alan-ai/alan-sdk-react-native
```

**Comment by kestvir** [comment]
> @kestvir
> yes, it should be inside of your project folder.
> 
> Also could you try to create a new project and install Alan SDK with next commands?
> 
> ```
> npx react-native init AwesomeProject
> cd AwesomeProject/
> npm i @alan-ai/alan-sdk-react-native
> ```

Thanks for your suggestion. I followed the instructions and after fixing couple of issues with gradel managed to successfully import `{AlanView}` , but I still had to copy the necessary files from `node_modules`, but the important thing is that it works.

I suspect that there is some issue wit the project which is setup with expo cli or the expo version which I am using in my main app. Could I share the repo here for you to take a look?

**Comment by snyuryev** [comment]
@kestvir are you running iOS or Android? I will investigate background color issue

Also we don't have mic icon for mobile sdk at this moment (as you have seen on web)

ps: could we close this issue as resolved?

**Comment by kestvir** [comment]
> @kestvir are you running iOS or Android? I will investigate background color issue
> 
> Also we don't have mic icon for mobile sdk at this moment (as you have seen on web)
> 
> ps: could we close this issue as resolved?

I will close this as resolved after you next reply, if that is ok.  

I wanted to ask if you had any idea why the `UIManager` can't find Alan components using [this setup](https://github.com/kestvir/recipe-reader/blob/alan-ai-not-working-example/package.json)?

Also, besides the background there are other issues mentioned in my previous post in the Edit2 (button moves around, can be dragged of the screen, text to speech not working). Pleas look into those as well.

**Comment by snyuryev** [comment]
@kestvir We will investigate this issue with UIManager. 

For rest of the list I suggest just create separate issue(s) and specify details about platform.
